### ISSUE TITLE
GET /{api_id}/versions/{version_id}/definitions/{definition_id} Entity is queried by technical id

### ISSUE THREAD

**Issue by maschleg** [zalando-incubator/api-discovery#110]
**Current behavior:**
GET /{api_id}/versions/{version_id}/definitions/{definition_id} 
queries the table api_version via technical id

```
apiRepository.findOne(id)
```

Impact: 
Api definition <-> implementation mismatch . Client receives wrong Resource. 

**Expected behavior:**

ApiEntity should be selected by api_id and version_id and definition_id

```
apiRepository.findByApiNameAndApiVersionAndDefinitionId(..)
```

**Comment by mfellner** [comment]
@maschleg @fmueller This issue only affects `org.zalando.apidiscovery.storage.api.ApiService#getApiDefinitionDto`, I believe since the old API should probably be left unchanged.

In that case this method currently fetches API definitions directly by definition_id (definition hash) and the other path parameters are ignored (see `org.zalando.apidiscovery.storage.api.ApiResourceController#getApiDefinition`).

However I would think that api_id and version_id should definitely be part of the query as well (as @maschleg suggested). What do you think?

**Comment by mfellner** [comment]
Ok, so after looking at the code and the API definition in more detail, there is a lot of ambiguity:

ApiEntity's relevant properties:
* id: Long
* apiName: String
* apiVersion: String
* definitionId: Integer
* definitionHash: String

According to the code and this ticket's literal description and the parameter names in the API yaml, id, apiVersion and definitionId should be used. However according to this ticket's intent I think apiName, apiVersion and definitionHash should be used, I think.

More questions:
* Why is definitionId an int and not a long?
* Why are the parameter names in the API yaml not referencing the presumably correct properties of ApiEntity?
* Why are we using the long/int IDs in the code at all? They should remain in the database, imo.

**Comment by maxim-tschumak** [comment]
@mfellner 

> org.zalando.apidiscovery.storage.api.ApiService#getApiDefinitionDto, I believe since the old API should probably be left unchanged.

All code from `org.zalando.apidiscovery.storage.api` package is used for the new API.

> Why is definitionId an int and not a long?

`definition_id` a sequential number of an API definition with the same semantic version (`api_version`) and is a part of the composite index (`api_name`, `api_version`, `definition_id`). In this case, `BIGINT` is not needed.
Example:
ApiEntity(`api_name=meta-api`, `api_version=1.0`, `definition_id=1`, definition=`version:1.0,diff:a`)
ApiEntity(`api_name=meta-api`, `api_version=1.0`, `definition_id=2`, definition=`version:1.0,diff:b`)

IMO, we should remove the auto generated id field of the `api_version` table since we already have the compound unique index `api_version_api_name_version_definition_id_idx`.

> Why are we using the long/int IDs in the code at all?

I believe `org.zalando.apidiscovery.storage.api.ApiResourceController#getApiDefinition` is the only place in the domain logic where we use technical id. And this will change when this issue/bug is implemented :)

I hope I could clarify your questions.

**Comment by fmueller** [comment]
To wrap up: it is a bug and should be fixed. And this bug only affects new API.
