### ISSUE TITLE
Keep text in search box in api dropdown list

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/api-discovery#29]
Mentioned by @mkulak: it would be nice if the input text would stay in search field of api dropdown list after search was submitted.

**Comment by mkulak** [comment]
Use case:

I open https://swagger.architecture.zalan.do, click on dropdown "Search an API" and type "Stock". 
I get 4 results and click on "Stock service (stock)". but then I realise that it's not  I'm looking for.  So I open dropdown once again, type "Stock" again and choose other result. Then I find out that stock APIs are related to each other and I want to switch back and forth between them quickly. But I can't do that because I need to retype "Stock" all the time.
